### ISSUE TITLE
turtleblocks.py should load same plugins as Sugar version by default

### ISSUE THREAD

**Issue by icarito** [sugarlabs/turtleart-activity#31]
Try to load graphics-xo-child.ta from turtleblocks.py (gnome version). Some blocks don't appear and it will crash.

**Comment by icarito** [comment]
Here's the console output:

```
$ ./turtleblocks samples/graphics-sunrise.ta 
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
string: dock mismatch 2 > 0
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
ERROR: block type not found string
```

**Comment by walterbender** [comment]
I cannot reproduce this error. What version are you running?

On Mon, Jun 20, 2016 at 5:18 PM, Sebastian Silva <notifications@github.com>
wrote:

> Here's the console output:
>
> $ ./turtleblocks samples/graphics-sunrise.ta
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> string: dock mismatch 2 > 0
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
> ERROR: block type not found string
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sugarlabs/activity-turtleart-gtk2/issues/31#issuecomment-227272597>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADz74Vm2dtpIAXy0-PLp89dwO1sbc4r9ks5qNwOogaJpZM4I6Iso>
> .
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org
<http://www.sugarlabs.org>

**Comment by icarito** [comment]
I'm using current git master branch (on Debian 8).

**Comment by icarito** [comment]
Notice the grey boxes also:
![image](https://cloud.githubusercontent.com/assets/199755/16211545/c47f03ba-3707-11e6-82f7-25e83e8c4cfc.png)

**Comment by icarito** [comment]
Note this only happens when running outside Sugar with the `turtleblocks` script.

**Comment by AlanJAS** [comment]
Is not a problem itself. You have unload the "turtleextras" plugin. Mark the plugin in "Extensiones" menu and try again.
The problem could be let the user disable the turtleextras plugin, but that is other discussion.

**Comment by icarito** [comment]
Ah I see! Thanks! I'm renaming this issue because I still think it's an issue. There is no warning to the user in this case.

**Comment by walterbender** [comment]
I am not sure what else can be done here. I believe that the current code will load the same plugins since both are using the same GSettings. The "warning" is the appearance of grayed out blocks, which indicate a missing plugin.
