### ISSUE TITLE
Canvas drawn with black background

### ISSUE THREAD

**Issue by quozl** [sugarlabs/turtleart-activity#45]
On Fedora 27 on Raspberry Pi 3, the canvas is drawn with a black background.

There are no unusual warnings.

**Comment by walterbender** [comment]
Running from Sugar or the cmdline?
Does the clear block render a blue background?

**Comment by quozl** [comment]
> Running from Sugar or the cmdline?

Sugar.

> Does the clear block render a blue background?

Not able to test for some time, sorry.  Doesn't happen in Ubuntu 18.04.

**Comment by quozl** [comment]
Tested on Rasbpian Stretch 2018-06-27, no problem happens.  Given that this was seen only with Fedora 27, I'll assume it was a Fedora 27 problem.
