### ISSUE TITLE
Python GI API version warnings

### ISSUE THREAD

**Issue by quozl** [sugarlabs/turtleart-activity#46]
TurtleBlocks-216 on Fedora 27 warns about

* `GConf` in `TurtleActivity.py` line 34,
* `PangoCairo` in `sprites.py` line 86.

**Comment by walterbender** [comment]
GConf is no longer used.
I don't see the error from the cmdline on F28.

**Comment by quozl** [comment]
Is fixed as of 2781942, thanks.
