### ISSUE TITLE
flake8 opportunities

### ISSUE THREAD

**Issue by quozl** [sugarlabs/turtleart-activity#58]
About 8463 flake8 errors are generated by;

```
python2 -m flake8 $(find . -name '*.py') | wc --lines
```

Work can be broken down into main program, plugins, and others.

Change python2 to python3 once the activity has been ported.

**Comment by ananyaarun** [comment]
@quozl , i would like to work on this issue .... can u please provide more information ? Thanks.

**Comment by chimosky** [comment]
@ananyaarun see #60

**Comment by quozl** [comment]
Thanks.  It’s really complicated.  I’d still like Turtle Confusion and Turtle Art sources to converge before fixing small issues like flake8, because those issues make it harder to converge.

**Comment by quozl** [comment]
As I've abandoned the converging of Turtle Confusion and Turtle Art sources, the remaining work on flake8 fixes is being reconsidered; excluded from this are any sources that are maintained elsewhere; which are CollabWrapper, the odfpy source, and sugariconify.
