### ISSUE TITLE
user is able to horizontally scroll even when there is no need to

### ISSUE THREAD

**Issue by pidddgy** [sugarlabs/turtleart-activity#75]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/30125762/71522659-a0b8f180-2893-11ea-97a5-a1e0bd8997af.png">

<img width="937" alt="image" src="https://user-images.githubusercontent.com/30125762/71522668-a9112c80-2893-11ea-80dc-e4acdf682b7b.png">

**Comment by Dimi20cen** [comment]
Isn't that how it's supposed to be to give the user more room for when it's needed?

**Comment by walterbender** [comment]
Yes... but the help message should probably appear in the visible part of the screen?

**Comment by Dimi20cen** [comment]
Ahhh yes I see, when a new help message is created, it starts at the start of the screen instead of starting at the visible part of it.
