### ISSUE TITLE
Fails to Start

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/turtleart-activity#86]
Activity fails to start and this is seen in the logs.
```GLib-GIO-ERROR **: 06:16:20.565: Settings schema 'org.laptop.TurtleArtActivity' does not contain a key named 'plugins-list'```.

**Comment by Ark74** [comment]
I'm having the same issue, is there any change we could address it?

**Comment by quozl** [comment]
Yes, please.  org.laptop.TurtleArtActivity.gschema.xml has a key plugins, but not a key plugins-list, so this may be a very simple mistake.

**Comment by Ark74** [comment]
What should be right, changing the schema to `plugins-list` or changing the TurtleArtActivity.py to `plugins` ?

**Comment by quozl** [comment]
I don't know.  I'm just guessing.  Perhaps look at the history of change in those areas, using git blame.

**Comment by Ark74** [comment]
Making the change on TurtleArtActivity.py (plugin-list > plugins) on a running env  allows to start the activity, building to see if anything breaks on a clean install.

**Comment by quozl** [comment]
So just to check, you were trying to use _master_ rather than the latest release tag v220?  I've just looked through the commits since that release, and there's a good chance there may be other discoveries to make.  What you have found already looks like nobody has been testing.

**Comment by Ark74** [comment]
> I don't know. I'm just guessing. Perhaps look at the history of change in those areas, using git blame.

That seems to fix the issue, I'll make a PR and we can review it maybe (not in a sunday) later, thanks for the heads up.

> So just to check, you were trying to use master rather than the latest release tag v220? 

Checking.... but there is a good chance we are using master.

**Comment by quozl** [comment]
http://download.sugarlabs.org/sources/sucrose/fructose/ is where releases are made for this source repository.

https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#checklist---maintainer is the release process checklist.

**Comment by Ark74** [comment]
> Checking.... but there is a good chance we are using master.

Yep, master :cold_sweat:

**Comment by chimosky** [comment]
@Ark74 said;
> Making the change on TurtleArtActivity.py (plugin-list > plugins) on a running env allows to start the activity, building to see if anything breaks on a clean install.

Yes, that is expected and I haven't taken a look to see if that should be the fix and one way to determine that is to see what the expected type of `plugins` is and if `plugins-list` is of the same type. 

> Edit: Well, both master and v220 has the same issue, so should I hold any PR then?

Please make a PR if you have a fix.

> I think it will be wise to package releases instead of code from master, that will change our workflow, so we'll need to adjust on that path in the coming release.

Our releases are packaged as @quozl has shared above, and they're packaged from master because that's the branch that's released.

**Comment by Ark74** [comment]
Fixed by #86

**Comment by chimosky** [comment]
Yes, thanks for pointing that out @Ark74. Closing as issue has been fixed.
